# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078fa0941f73c41990dc5acd90ca04b0b8b486acbf8290856dcce304fa2b47a8fa38a294d2b57ee6ddc7a58f720d55746189d6aaa666d6b30aad4c08bd8ba211

test:
  secret_key_base: 9572bfeb8a359729f6f03bf44e5dab894153f7d382648c3686440c6dec5bb2c4b57902a900f5db6a786d9ee77910ae6181e0b59c8c87ae5495c812d644cd9f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
